{"name":"DataBaseTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n ","trace":"java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \r\n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)\r\n\tat oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)\r\n\tat oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)\r\n\tat oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)\r\n\tat oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)\r\n\tat java.sql.DriverManager.getConnection(Unknown Source)\r\n\tat java.sql.DriverManager.getConnection(Unknown Source)\r\n\tat Day10Maven.DataBasePara.DataBaseTest(DataBasePara.java:24)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\nCaused by: oracle.net.ns.NetException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \r\n\tat oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:272)\r\n\tat oracle.net.ns.NSProtocol.connect(NSProtocol.java:263)\r\n\tat oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1360)\r\n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:486)\r\n\t... 32 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1600087069260,"stop":1600087070063,"uuid":"9a053d0a-9975-4eb3-b7fe-d370e2b57f1d","historyId":"b5588b5c39c30c2f8d9493493ea7350b","fullName":"Day10Maven.DataBasePara.DataBaseTest","labels":[{"name":"package","value":"Day10Maven.DataBasePara"},{"name":"testClass","value":"Day10Maven.DataBasePara"},{"name":"testMethod","value":"DataBaseTest"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"Day10Maven.DataBasePara"},{"name":"host","value":"DESKTOP-3EGAET6"},{"name":"thread","value":"5740@DESKTOP-3EGAET6.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}